FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --prefer-offline || npm install --prefer-offline || npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
