
services:

  db:
    image: postgres:15
  #  container_name: postgres-db
    environment:
      POSTGRES_DB: PFAdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cesar
    ports:
      - "5432:5432"

  backend:
    build: .
   # container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
   # container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true