sonar.projectKey=CareerPilot
sonar.projectName=CareerPilot
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.vite/**,**/venv/**,**/migrations/**,**/__pycache__/**,**/media/**

sonar.sourceEncoding=UTF-8