# Generated by Django 5.2.12 on 2026-03-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cvs', models.IntegerField(default=0)),
                ('total_interviews', models.IntegerField(default=0)),
                ('average_ats_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_matching_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
