# Generated by Django 5.2.12 on 2026-05-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0005_cv_photo_path'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingresult',
            name='job_offer',
        ),
        migrations.RemoveField(
            model_name='matchingresult',
            name='cv',
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('score', models.IntegerField()),
                ('matching_skills', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_analysis.cv')),
            ],
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
        migrations.DeleteModel(
            name='MatchingResult',
        ),
    ]
