# Generated by Django 5.2.12 on 2026-04-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0002_cvanalysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysisresult',
            name='found_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvanalysisresult',
            name='structure_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
