# Generated by Django 5.2.12 on 2026-05-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0003_cvanalysisresult_found_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysisresult',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvanalysisresult',
            name='ai_optimization',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizedcv',
            name='improvement',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optimizedcv',
            name='optimized_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizedcv',
            name='score_optimized',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optimizedcv',
            name='score_original',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optimizedcv',
            name='generated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
