# Generated by Django 5.2.12 on 2026-05-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0004_cvanalysisresult_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
